[package]
name = "lsp_services"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
dirs = "6.0.0"
log = "0.4.27"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
walkdir = "2.5.0"
