[problem.translate_chibicc]
# 需要进行评测的 docker image id
docker_image = "debian:latest"
# docker 镜像里代码生成阶段的工作目录。
codegen_workdir = "/tmp"
# docker 镜像里代码生成阶段需要运行的命令（不是Shell命令，不能带有管道等Shell操作符）。
codegen_command = "ls -l"
# docker 镜像里代码生成阶段日志输出路径。
codegen_logfile = "/tmp/run.log"
# docker 镜像里生成的代码所在的目录。
codegen_resultdir = "/tmp"
# docker 镜像里构建生成的代码的命令，并假设工作目录是 codegen_resultdir。
build_command = "touch translated_chibicc"
# docker 镜像里生成的二进制可执行文件路径。
exe = "/tmp/translated_chibicc"

[problem.translate_littlefs_fuse]
docker_image = "debian:latest"
codegen_workdir = "/tmp"
codegen_command = "ls -al"
codegen_resultdir = "/tmp"
codegen_logfile = "/tmp/run.log"
build_command = "touch translated_littlefs_fuse"
exe = "/tmp/translated_littlefs_fuse"
